#!/bin/bash
TARGET="nyxgo"
SCRIPT="start.run"
TEMP_CORE="core_data"
mkdir "$TARGET"
cp "../core.py" "../loadNapCat.cjs" "../source.json" "../requirements.txt" "./$TARGET"
tar -cJf "$TEMP_CORE" "$TARGET/"
cat ./template.sh "./$TEMP_CORE" > "$SCRIPT"
chmod +x "$SCRIPT"
rm -rf "./$TARGET" "./$TEMP_CORE" 
echo "自解压脚本制作完毕，已输出至$SCRIPT"
